# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
# check these on https://fabricmc.net/develop/
minecraft_version=26.1
loader_version=0.18.4

# Mod Properties
mod_version=2.1.2
maven_group=io.github.juuxel
archives_base_name=WoodsAndMires

# Dependencies
fabric_version=0.144.1+26.1
terrablender_version=26.1-26.1.0.1
polymer_version=0.16.0-pre.2+26.1-rc-2
typesafe_config_version=1.4.3
jgrapht_version=1.5.2
terraform_api_version=17.0.0-alpha.5
