# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
# check these on https://fabricmc.net/develop/
minecraft_version=26.2
loader_version=0.19.3

# Mod Properties
mod_version=2.1.2
maven_group=io.github.juuxel
archives_base_name=WoodsAndMires

# Dependencies
fabric_version=0.154.2+26.2
terrablender_version=26.2-26.2.0.0.2
polymer_version=0.17.3+26.2
typesafe_config_version=1.4.3
jgrapht_version=1.5.2
terraform_api_version=17.0.0-beta.5
