name: build
on: [pull_request, push]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v7
      - name: read java version
        id: java
        run: echo "version=$(grep -oP '^java_version=\K.*' gradle.properties)" >> "$GITHUB_OUTPUT"
      - name: setup jdk
        uses: actions/setup-java@v6
        with:
          java-version: ${{ steps.java.outputs.version }}
          distribution: 'microsoft'
      - name: setup gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          validate-wrappers: true
      - name: build
        run: ./gradlew build
      - name: capture build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Artifacts
          path: build/libs/
