name: release
on: [workflow_dispatch]

permissions:
  contents: write
  actions: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: read java version
        id: java
        run: echo "version=$(grep -oP '^java_version=\K.*' gradle.properties)" >> "$GITHUB_OUTPUT"
      - name: setup jdk
        uses: actions/setup-java@v6
        with:
          java-version: ${{ steps.java.outputs.version }}
          distribution: 'microsoft'
      - name: setup gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          validate-wrappers: true
      - name: generate changelog
        uses: FabricMC/fabric-action-scripts@v3
        id: changelog
        with:
          context: changelog
          workflow_id: release.yml
      - name: publish mods
        run: ./gradlew publishMods
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHANGELOG: ${{ steps.changelog.outputs.changelog }}
